### PR TITLE
+(feat): Add optimizations and useOriginalFileNames to default unit

### PR DESCRIPTION
**Pull request by Frankie-B**
@mm-paulie so this is my first feature, I have added the optimisations and useOriginalFileNames to be included when a new plain display unit set is created.

### CODE REVIEW

**Review by mm-paulie — CHANGES_REQUESTED** [review]
Can you first only add the optimizations and useOriginalFileNames? Now I see the webfontloader and gsap 3.8 being added as well in the package.json

**Comment by mm-paulie** [comment]
I see you added gsap 3.6 again, changed it to 3.8

**Review by mm-paulie — COMMENTED** [review]
Maybe we can only add 1 font?

**Comment by mirkovw** [comment]
@Frankie-B @mm-paulie How are we doing with this PR ?

**Comment by Frankie-B** [comment]
@mirkovw when you get a moment can you merge in the above changes.

**Comment by mirkovw** [comment]
@Frankie-B It says Paulie still requested some changes

**Comment by Frankie-B** [comment]
Font sub-setting and fitText are working and implemented to be included by default.

**Pull request closed without merging**
